### ISSUE TITLE
Linking needs to know relative link position of current buffer.

### ISSUE THREAD

**Issue by kandodev** [ElPiloto/telescope-vimwiki.nvim#2] opened 2022-01-09 08:33 UTC
When I try to link to a page using `Telescope vimwiki link`, if I'm in a vimwiki buffer, it assumes that page is the root vimwiki page and links accordingly. But if I'm already nested, it needs to go back up sometimes (e.g: ../../some_other/blah.md)

**Comment by ElPiloto** [comment] 2022-01-10 00:04
Thanks for reporting this issue @codevion .  Just submitted a fix, please update and write back here if you find any issues.

**Comment by kandodev** [comment] 2022-01-10 02:27
Alright, it seems to work great on non index.md pages. But I have a nested structure of index.md pages where I have an index.md page inside each folder. Whenever I try to link on a subfolder index.md page, it assumes I'm in the root index.md I guess?

**Comment by ElPiloto** [comment] 2022-01-10 14:04
Hmmm, can you give an example of directory layout where this fails? With the following directory structure below, it seems to be working fine:
```
wiki_root/index.md
wiki_root/coding/index.md
wiki_root/coding/web_dev.md
```
Then from `wiki_root/coding/web_dev.md`:

- linking to `wiki_root/coding/index.md`  produces the expected link: `index.md`
-  linking to `wiki_root/index.md` produces the expected link: `../index.md`

And conversely, from `wiki_root/coding/index.md` linking to `wiki_root/coding/web_dev.md` produces the expected link: `web_dev.md`

**Comment by kandodev** [comment] 2022-01-10 18:23
So think two different substructures:
`root/coding/index.md`
`root/linux/arch.md`

Trying to link to `arch.md` from `index.md` tries to find path `root/coding/linux/arch.md`.

**Comment by ElPiloto** [comment] 2022-01-10 22:26
Thanks for the extra info.  I'm still not reproducing this bug unfortunately.  With my analogous directory structure:

```
wiki_root/index.md
wiki_root/coding/index.md
wiki_root/coding/web_dev.md
wiki_root/family/values.md
```
and then from `wiki_root/coding/index.md`:

- linking to `wiki_root/family/values.md`  produces the expected relative link: `../family/values`

Not sure where to go from here.  I don't typically use nested index.md pages.  Is there a special way to make them or do you just make them like any other page in a subdirectory i.e. from `wiki_root/index.md` add a link to `coding/index.md` and then hit enter to make that page?  Do you explicitly define the nested index pages as their own vimwikis?  In any case, can you post your full vimwiki config?

**Comment by ElPiloto** [comment] 2022-01-27 23:05
Closing this since I cannot reproduce it and no follow up from OP.

**Closed as completed by ElPiloto** 2022-01-27 23:05 UTC
